### ISSUE TITLE
Equivalence between RA and GLS

### ISSUE THREAD

**Issue by sahirbhatnagar** [lzhangdc/Robust-Allele-based-Regression-Framework#1]
Really nice work. This isn't really an issue; I'm just posting a simulation showing Equation (7) in the Biometrics paper looks like a generalized least squares problem, that can be solved using `nlme::gls()` with a compound symmetry correlation structure. This could potentially make the code more flexible, i.e., not needing separate functions for when covariates are included or not. It also can lend to other correlation structures, e.g., a general symmetric correlation. There is also the added benefit of obtaining confidence interval estimates 'for free' and seamlessly integrating interactions terms, categorical covariates, ect. The code can be found [on my fork](https://github.com/sahirbhatnagar/Robust-Allele-based-Regression-Framework/blob/main/RA_functions.R). Specifically, lines [131-164](https://github.com/sahirbhatnagar/Robust-Allele-based-Regression-Framework/blob/main/RA_functions.R#L131-L164) is the function I implemented. Happy to discuss further if it's of interest. 

``` r
source("~/git_repositories/Robust-Allele-based-Regression-Framework/RA_functions.R")
########################################################################
########################################################################
#### Function inputs:
#### - g: genotype vector (G=0, 1, 2), n x 1 vector
#### - y: phenotype traits, n x J matrix 
#### - z: covariates, n x K matrix
#### - HWE: logical, TRUE or FALSE
########################################################################
#### Function output:
#### - p-value of the RA association test 
########################################################################
########################################################################

nIndep <- 50000; geno_prob <- c(0.64, 0.32, 0.04)
g_test <- sample(0:2, size=nIndep, replace=T, prob=geno_prob)
y_test <- cbind(replicate(3, rnorm(nIndep)), sample(0:1, size=nIndep, replace=T, prob=c(0.8, 0.2)))
z_test <- cbind(replicate(5, rnorm(nIndep, mean=3, sd=3)), replicate(10, rnorm(nIndep, mean=4, sd=4)))

## Independent samples, 3 continuous and 1 binary phenotype traits, no covariates, no assumption of HWE
RA_assoc_indep(g=g_test, y=y_test, z=NULL, HWE=F, nlme = F)
#>        pval     RA_stat         rho 
#> 0.827765882 1.493648924 0.002693233
RA_assoc_indep(g=g_test, y=y_test, z=NULL, HWE=F, nlme = T)
#>        pval     RA_stat     rho.Rho 
#> 0.827761935 1.493671232 0.002678166

## Independent samples, 3 continuous and 1 binary phenotype traits, 4 covariates, no assumption of HWE
RA_assoc_indep(g=g_test, y=y_test, z=z_test, HWE=F, nlme = F)
#>        pval     RA_stat         rho 
#> 0.824420991 1.512522395 0.002553663
RA_assoc_indep(g=g_test, y=y_test, z=z_test, HWE=F, nlme = T)
#>       pval    RA_stat    rho.Rho 
#> 0.82441693 1.51254525 0.00253842
```

<sup>Created on 2022-10-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lzhangdc** [comment]
Hi,

Thank you so much for the comment.

The reason that we have customized functions for RA (and for different data scenarios), is essentially because RA is designed for fast scans in genome-wide association studies (GWAS) to identify potentially disease susceptibility loci (DSL). In that regard, RA is supposed to work fast to scan through millions of SNPs. Our proposed RA framework can run one GWAS with half a million SNPs in less than 24 hours on a single CPU core. 

I agree that under some scenarios that gls can be a substitute for our proposed RA framework, but the computational cost of gls can be very high in that case. And the memory requirement will be higher than RA due to the iterative estimation procedure. 

Although "complementary" CI estimates are very sounding, they are not "for free" but in sacrifice of computational efficiency. I also want to re-emphasize that our RA framework is primarily designed for genetic association testing purpose. 

Thank you very much again for your thoughtful comments. I'm more than happy to discuss more if needed. 

Best wishes,
Lin
